2019-10-05 11:04:29,776 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.7
2019-10-05 11:04:29,776 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': '/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2019-10-05-11-04-29-mpf-Brian-Evans-MBP.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-10-05 11:04:29,776 : INFO : Machine : MPF path: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf
2019-10-05 11:04:29,776 : INFO : Machine : Machine path: /Users/brianevans/Projects/HeistMPF
2019-10-05 11:04:29,776 : INFO : Machine : Platform: darwin
2019-10-05 11:04:29,776 : INFO : Machine : Python executable location: /Users/brianevans/Projects/Heist2/bin/python3
2019-10-05 11:04:29,776 : INFO : Machine : Python version: 3.6.8 (64-bit)
2019-10-05 11:04:29,776 : INFO : Machine : Machine config file #1: config.yaml
2019-10-05 11:04:29,778 : WARNING : ConfigProcessor : Config file in cache changed: /Users/brianevans/Projects/HeistMPF/config/config.yaml
2019-10-05 11:04:29,778 : INFO : ConfigProcessor : Loading config from file /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml.
2019-10-05 11:04:29,863 : INFO : ConfigProcessor : Loading config: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml
2019-10-05 11:04:29,871 : INFO : ConfigProcessor : Loading config from file /Users/brianevans/Projects/HeistMPF/config/config.yaml.
2019-10-05 11:04:29,903 : ERROR : root : Error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'
Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 198, in load
    config = self.process(f)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 114, in construct_document
    for dummy in generator:
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml: 'Key "p" was defined multiple times in config   in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 14, column 5'
