2019-10-05 12:50:09,547 : INFO : Machine : Mission Pinball Framework Core Engine v0.52.7
2019-10-05 12:50:09,547 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': '/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2019-10-05-12-50-09-mpf-Brian-Evans-MBP.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'smart_virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-10-05 12:50:09,547 : INFO : Machine : MPF path: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf
2019-10-05 12:50:09,548 : INFO : Machine : Machine path: /Users/brianevans/Projects/HeistMPF
2019-10-05 12:50:09,548 : INFO : Machine : Platform: darwin
2019-10-05 12:50:09,548 : INFO : Machine : Python executable location: /Users/brianevans/Projects/Heist2/bin/python3
2019-10-05 12:50:09,548 : INFO : Machine : Python version: 3.6.8 (64-bit)
2019-10-05 12:50:09,548 : INFO : Machine : Machine config file #1: config.yaml
2019-10-05 12:50:09,549 : WARNING : ConfigProcessor : Config file in cache changed: /Users/brianevans/Projects/HeistMPF/config/config.yaml
2019-10-05 12:50:09,549 : INFO : ConfigProcessor : Loading config from file /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml.
2019-10-05 12:50:09,632 : INFO : ConfigProcessor : Loading config: /Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/mpfconfig.yaml
2019-10-05 12:50:09,639 : INFO : ConfigProcessor : Loading config from file /Users/brianevans/Projects/HeistMPF/config/config.yaml.
2019-10-05 12:50:09,667 : ERROR : root : YAML error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml. Line 147,Position 1: while scanning a simple key
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 146, column 5
could not find expected ':'
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 147, column 1
Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 198, in load
    config = self.process(f)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 547, in parse_block_mapping_key
    if self.scanner.check_token(KeyToken):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 159, in check_token
    while self.need_more_tokens():
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 196, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 345, in stale_possible_simple_keys
    "could not find expected ':'", self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 146, column 5
could not find expected ':'
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 147, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/commands/game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/machine.py", line 175, in __init__
    self._load_config()
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/machine.py", line 444, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/core/file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "/Users/brianevans/Projects/Heist2/lib/python3.6/site-packages/mpf/file_interfaces/yaml_interface.py", line 205, in load
    raise ValueError(msg)
ValueError: YAML error found in file /Users/brianevans/Projects/HeistMPF/config/config.yaml. Line 147,Position 1: while scanning a simple key
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 146, column 5
could not find expected ':'
  in "/Users/brianevans/Projects/HeistMPF/config/config.yaml", line 147, column 1
